#!/bin/bash
if [[ -d ${HOME}/.oh-my-zsh/custom ]];then
    mv ${HOME}/.oh-my-zsh/custom ${HOME}/.oh-my-zsh.custom/
    pushd ${HOME}
    git clone git@github.com:lanthean/oh-my-zsh.custom.git .oh-my-zsh.custom
    git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete
    popd
fi
ln -snf ${HOME}/.oh-my-zsh.custom/custom ${HOME}/.oh-my-zsh/